server:
  port: 8080

database:
  - user: admin
    password: admin
    host: localhost
    dbName: shopDEV
  - user: user
    password: user
    host: localhost
    dbName: shopDEV

security:
  jwt:
    key: ffff111
